spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: posts-service
  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${PORT}

security:
  jwt:
    secret-key: ${SECRET_KEY}
    expiration-time: ${EXP_KEY}
